citrination_client/client.py, setup.py
@maxhutch This fixes a bug that was happening when no search hits were returned in the iteration. In that case `partial_results.hits` was equal to None and an exception was thrown when calling hits.extend(partial_results.hits). 
I also threw the sleep into its own little if/else statement so that it doesn't sleep when no hits are returned (or on the last iteration loop).
=> check for no hits when iterating through results

citrination_client/search/pif/query/pif_query.py, setup.py
@maxhutch This just adds support for a new search feature we are putting in - the ability to return a random sets of hits from your search request. The idea is that you might want a random sampling of hits each time that you make a query.
=> allow for random query results

README.md, citrination_client/client.py, citrination_client/tests/test_client.py, requirements.txt, setup.py
Python3 requests are encoded byte-strings, so they need a decode.  It doesn't bother the python2 workings, which the test will enforce.
CC: @kjaym
=> Bugfix: python content decode

README.md
Python versions < 2.7.9 have SSL certificate problems that can cause
clients to reject valid server certificates.
cf. http://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
This manifests as:
```
In [5]: print("Found {} PIFs in dataset {}".format(client.search(query_dataset).total_num_hits, dataset_id))
/home/maxhutch/anaconda2/lib/python2.7/site-packages/requests-2.10.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see …
```
=> Set required Python version >= 2.7.10.

citrination_client/search/pif/query/__init__.py, citrination_client/search/pif/query/chemical/chemical_field_operation.py, citrination_client/search/pif/query/chemical/chemical_field_query.py, citrination_client/search/pif/query/chemical/composition_query.py, citrination_client/search/pif/query/core/base_field_operation.py, citrination_client/search/pif/query/core/base_field_query.py, citrination_client/search/pif/query/core/classification_query.py, citrination_client/search/pif/query/core/field_operation.py, citrination_client/search/pif/query/core/field_query.py, citrination_client/search/pif/query/core/file_reference_query.py, citrination_client/search/pif/query/core/id_query.py, citrination_client/search/pif/query/core/name_query.py, citrination_client/search/pif/query/core/pages_query.py, citrination_client/search/pif/query/core/process_step_query.py, citrination_client/search/pif/query/core/property_query.py, citrination_client/search/pif/query/core/quantity_query.py, citrination_client/search/pif/query/core/reference_query.py, citrination_client/search/pif/query/core/source_query.py, citrination_client/search/pif/query/core/system_query.py, citrination_client/search/pif/query/core/value_query.py
@maxhutch This looks like a lot, but it just deprecates FieldOperation and ChemicalFieldOperation in favor of FieldQuery and ChemicalFieldQuery. This is more consistent with the naming throughout the rest of the query language. 
Backwards compatibility is maintained through e.g. https://github.com/CitrineInformatics/python-citrination-client/blob/d98a517a8b5fe588ee2e6f33fc3f895af0d02494/citrination_client/search/pif/query/core/field_operation.py. 
Are we we merging into develop or master? Let me know if it's the former and I will close this and open a new PR.
=> Deprecate FieldOperation in favor of FieldQuery and version to 1.3.0

citrination_client/client.py
Maintains backward support by looking for 404 errors and trying the old csv2models-based URL.
=> Adding support for predictions on data views

citrination_client/tests/test_client.py
The ruby app requires that a user not have more than one dataset
with the same name. Until recently there was a bug in the ruby
layer that prevented that validation from happening correctly.
Now that that bug is fixed, we need to make sure these tests run
in a way that creates a dataset with a new name each time.
=> Make Tests Conform To Dataset Name Validation

citrination_client/search/pif/query/core/classification_query.py, citrination_client/search/pif/query/core/id_query.py
The setters in id_query and classification_query were not actually setting anything. This fixes that.
@eantono @maxhutch @mcgalcode
=> bugfix - id/classification query setters did not assign values

citrination_client/client.py
By requiring the use of server side encryption in the buckets used in the
back end, we require that the `x-amz-acl` and `x-amz-server-side-encryption`
headers be present on the request to the presigned url that uploads files.
This commit adds the necessary headers.
=> Add Necessary Headers To Upload PUT Requests to S3

citrination_client/tests/test_client.py
The from_distribution predictions are noisier (and more robust), so
let's relax the tolerances.  Plus, we test for correctness elsewhere,
so doing such fine grained tests isn't particularly motivated here.
=> Relaxing the prediction tolerances

citrination_client/client.py
In case users have to proxy through a URL, this adds support for including the proxy list in a CitrinationClient instance.
=> Allow proxies to be supplied to the client

citrination_client/client.py
We are going to start returning a 204 to indicate a query timeout rather than a 524.
=> Support 204 return for query timeout as well as 524

citrination_client/data/tests/test_data_client.py, citrination_client/search/pif/tests/test_pif_query.py
- ensure that simple query generation test does not run
unless the tests are being run against public citrination
- give update dataset metadata test a 5 minute timeout window
since we were experiencing many timeout failures before
=> Fix Failing Tests

citrination_client/models/design/constraints/real_range.py, citrination_client/models/tests/test_models_client.py, citrination_client/util/maths.py, citrination_client/util/tests/test_maths.py, setup.py
Citrination requires that Infinity values be serialized
as strings rather than constants.
=> Hotfix - Infinity Serialization

citrination_client/base/response_handling.py, citrination_client/base/tests/test_response_handling.py, citrination_client/data/tests/test_data_client.py
Throws ResourceNotFound as opposed to CitrinationServerError
=> Throw Appropriate Exception For 404s

citrination_client/base/base_client.py, citrination_client/data/client.py, citrination_client/data/tests/test_data_client.py, citrination_client/models/client.py, citrination_client/search/client.py, setup.py
This PR adds an optional `proxies` parameter to the CitrinationClient. The proxies dict will be passed along to the requests module for all HTTP requests.
=> Add proxies param to the CitrinationClient (base)

.travis.yml
Currently, the deploy command fails because we run it on every listed python version we want to test. This is not necessary - just run deploy for 3.6 (arbitrary).
=> Only run deploy job on python 3.6 (still test for all)

citrination_client/models/service_status.py, citrination_client/models/tests/test_service_status.py, setup.py
It is not true that service statuses can't be ready with progress < 100.
=> Hotfix/validation => master

README.md
We have a nice set of tutorials for citrination-client, but unfortunately a link to the html version (compiling the .rst files from docs and the code snippets) does not exist from within the repo where people would look for it.
=> added link to html version of tutorials

README.md
Just added more links to connect all of our work. Pretty sure I branched from develop so I'm not sure what's failing...feel free to add this content however is easiest. It's only 1 extra line in the README.
=> added jupyter tutorials to README

citrination_client/client.py, citrination_client/data/tests/test_data_client.py, citrination_client/models/client.py, citrination_client/models/design/target.py, citrination_client/models/tests/test_models_client.py, citrination_client/views/client.py, citrination_client/views/tests/test_model_template_builder.py
This PR does 3 things:
1) Removes the old synchronous predict endpoint and replaces it with a polling helper
2) Scrubs the lambda that digs in and pulls top level functionality from subclients to be explicit with those calls (hit a conflict)
3) Consolidates model-related calls to the models client and tucks it into the data views client
=> [CT-356] Feature/refactor models client

citrination_client/views/client.py
Just protect this iteration over default descriptor results.
=> Don't raise an error on bad descriptor results

citrination_client/views/client.py, citrination_client/views/model_report.py
The ViewsClient#get_model_reports endpoint returns a list of
ModelReport instances.
The ModelReport class serves as a wrapper around the model report
JSON returned by Citrination, initially providing access to
model performance, settings, and feature importances.
=> Add ModelReport class and ViewsClient#get_model_reports endpoint

citrination_client/base/errors.py, citrination_client/data/client.py, citrination_client/data/ingest/__init__.py, citrination_client/data/ingest/client.py, citrination_client/data/ingest/ingester.py, citrination_client/data/ingest/ingester_list.py, citrination_client/data/tests/test_upload_result.py, citrination_client/data/upload_result.py
Create IngesterList and Ingester classes
These IngesterList class will serve to abstract away the list of
ingester dicts that are available on a Citrination deployment, allowing
consumers to find the ingester they want to use either via #find_by_id or
one or more #where calls.
The Ingester class serves as an abstraction of an ingester dict. It provides
methods for returning a copy of itself, finding an argument by name, and
serialization for submission to Citrination.
Create IngestClient
This client will be leveraged by the DataClient in order to retrieve
available ingesters, validate ingesters before submission, and to
handle ingest submissions.
Add custom ingestion endpoints to the DataClient
Add instantiation of the IngestClient to the DataClient's
initialization method.
Add …
=> Custom ingester support

docs/source/conf.py, docs/source/index.rst, setup.py
Add documentation notes regarding upgrading pycc from v4 to v6
Add notes to introduction regarding changes from pycc 4.x to 5.x,
and from 5.x to 6.x.
=> Release 6.0.1

citrination_client/__init__.py
I have this failure on Jenkins:
https://jenkins.corp.citrine.io/job/citrine-e2e-examples.pr/181/console
`dist_loc` is different than `here` because one uses a symbolic link:
```
here: /tmp/jenkins-40941e33/workspace/citrine-e2e-examples.pr/venv/lib64/python3.6/site-packages/citrination_client/_init_.py
dist_loc: /tmp/jenkins-40941e33/workspace/citrine-e2e-examples.pr/venv/lib/python3.6/site-packages
```
This fix uses `os.path.realpath` which should eliminate symbolic links that are in the path.
=> using os.path.realpath for symbolic link case
