CitrineInformatics/python-citrination-client

- .gitignore
- README.md
- setup.cfg
- setup.py
> getting ready for pypi

- citrination_client/client.py
> Adding automatic paging of long queries.

- citrination_client/client.py
- setup.py
@maxhutch This adds the `simple_chemical_search` method that lets us generate quick, common use case queries without having to build up entire PifQuery objects.
> first pass at simple chemical query

- citrination_client/client.py
- setup.py
Still debugging.
CC: @sparadiso @jsomara
> Adding predict call

- citrination_client/search/pif/query/core/property_query.py
- citrination_client/search/pif/query/core/value_query.py
@maxhutch This adds support for querying against files inside of Value objects, rather than just Property objects.
> add file reference query to value object

- citrination_client/search/dataset/query/dataset_query.py
- citrination_client/search/pif/query/pif_query.py
@sparadiso @maxhutch Adds support for random seeds
> add random seed support

- citrination_client/client.py
- setup.py
This release supports predictions on data views.
> Release 1.3.1

- README.md
- citrination_client/search/pif/query/pif_query.py
- citrination_client/search/pif/result/pif_search_result.py
Reverts CitrineInformatics/python-citrination-client#82
I hit the wrong button
> Revert "Feature/return csv"

- .travis.yml
- citrination_client/tests/test_client.py
> Bugfix: update t-sne test  and re-enable tests

- citrination_client/client.py
- setup.py
The wrong number of arguments were being passed into the post method.
> Bugfix with creating new dataset version

- citrination_client/client.py
- setup.py
> hotfix: create version

- citrination_client/client.py
- citrination_client/tests/test_client.py
> Adding "from_distribution" prediction type

- citrination_client/client.py
- citrination_client/search/dataset/result/dataset_search_hit.py
- citrination_client/search/dataset/tests/test_dataset_query.py
This adds a method to the client class that allows for searching on datasets. It also adds additional information to the dataset search hit class.
> Support for dataset queries

- citrination_client/search/pif/query/core/system_query.py
- citrination_client/search/pif/tests/test_pif_query.py
I'm trying to pull this into the release because (1) its relatively minor and (2) we need it for https://github.com/CitrineInformatics/pypif-sdk/pull/2
> Adding pif query by UID

- citrination_client/search/core/query/base_returning_query.py
- citrination_client/search/dataset/query/dataset_returning_query.py
- citrination_client/search/dataset/tests/test_dataset_query.py
- citrination_client/search/file/query/file_returning_query.py
- citrination_client/search/pif/query/pif_system_returning_query.py
- citrination_client/search/pif/tests/test_pif_query.py
Add timeout to search requests and test that makes sure and exception is raised when the request times out.
> Add timeout to search requests

- setup.py
> Resync develop

- setup.py
> Bump to version 3.3.2

- citrination_client/search/client.py
- citrination_client/search/pif/tests/test_pif_query.py
Adds a method that got removed a while ago that had
broken an untested method. Also adds tests for it the previously broken method.
> Fixes And Adds Tests For Simple Query Generation

- citrination_client/base/base_client.py
- citrination_client/data/client.py
- citrination_client/data/tests/test_data_client.py
- citrination_client/models/client.py
- citrination_client/search/client.py
- setup.py
This was not meant to go straight to master!
Reverts CitrineInformatics/python-citrination-client#194
> Revert "Add proxies param to the CitrinationClient (base)"

- citrination_client/client.py
I have tested this with a free proxy and it works as expected. Sorry for all the reflux here.
> Add proxies to CitrinationClient constructor

- citrination_client/client.py
- setup.py
> Release 4.6.0

- citrination_client/models/service_status.py
- citrination_client/models/tests/test_service_status.py
- setup.py
> Hotfix/validation => develop

- setup.py
Release the security patch update (requests)
> Release 4.6.2 -> master

- citrination_client/models/design/target.py
- citrination_client/models/design/tests/test_target.py
This just allows users to communicate specific value constraints to us through the API
> Add target response value support

- setup.py
> Release 4.7.0 -> develop

- citrination_client/views/descriptors/__init__.py
- citrination_client/views/descriptors/formulation_descriptor.py
> Adding formulation descriptor

- requirements.txt
> Patch out CVE-2018-18074

- setup.py
> Release/5.0.0 => develop

- citrination_client/views/descriptors/inorganic_descriptor.py
> Default to threshold 1.0

- docs/source/conf.py
- setup.py
> Release 5.1.1 -> develop

- citrination_client/__init__.py
- docs/source/conf.py
Note: holding on gh-pages until review
> Change relative path for local version lookup, added path to conf.py fix sphinx error 

- citrination_client/views/data_view_builder.py
Added a bit of detail to alleviate confusion. No functionality changes.
cc @Imperssonator @jspeerless @IAmGrootel
> update docstring to clarify modelling choice

- docs/source/conf.py
- setup.py
> Release 6.0.0

- docs/source/index.rst
Add notes to introduction regarding changes from pycc 4.x to 5.x,
and from 5.x to 6.x.
> Add documentation notes regarding upgrading pycc from v4 to v6

- docs/source/conf.py
- setup.py
> Release 6.0.1

- docs/source/conf.py
- docs/source/index.rst
- setup.py
> Release 6.1.0

- docs/source/conf.py
- docs/source/index.rst
- setup.py
This enables the definition of custom relations when configuring ML for a data view, via the AdvancedDataViewBuilder class.
> Release 6.3.0 - AdvancedDataViewBuilder

- citrination_client/data/client.py
It was missing `upload_with_template_csv_ingester`.
> Update DataClient members

- citrination_client/data/client.py
- citrination_client/data/ingest/client.py
- citrination_client/data/tests/test_data_client.py
https://citrine.atlassian.net/browse/CT-1191
> Add 'ingest log' retrieval route to PyCC

- docs/source/conf.py
- docs/source/index.rst
- setup.py
> [BackMerge] Bump Version & Add Release Notes

- setup.py
This release includes a bugfix where imports were failing due to dependencies locations being represented with symbolic links (#318).
> Release 6.5.1
